[Variables]

; Basic Settings
UpdateDivider=100

; Circle Settings
CircleSize=200
GapBetweenCircles=2
InnerColor=28,65,124
OuterColor=209,230,255
MovingSpeed=2
DateOffset=45

; Font Settings
UpperLevelFont=Nexa Bold
UpperLevelFontSize=40
UpperLevelFontColor=#OuterColor#
LowerLevelFontFace=Nexa Bold
LowerLevelFontSize=13
LowerLevelFontColor=#InnerColor#
DateFontSize=10

; Drive Settings 
Drive1=C
Drive2=E

; Weather Settings
WeatherLocation=USNY0170
WeatherUnit=F

UpperLevelHidden=0
LowerLevelHidden=1